name: foundation_fluttify_example
description: Demonstrates how to use the foundation_fluttify plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  foundation_fluttify:
    path: ../

flutter:
  uses-material-design: true