name: amap_map_fluttify
description: An `Amap` Map Component, Powered By `Fluttify` Compiler, A Dart Bindings Generator For Native SDK.
version: 2.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13"

dependencies:
  flutter:
    sdk: flutter
  
  uni_map_platform_interface:
    git:
      url: https://github.com/banyungong/flutter_amap.git
      path: amap/uni_map_platform_interface
  url_launcher: ^6.1.6
  foundation_fluttify:
    git:
      url: https://github.com/banyungong/flutter_amap.git
      path: amap/foundation_fluttify
  core_location_fluttify:
    git:
      url: https://github.com/banyungong/flutter_amap.git
      path: amap/core_location_fluttify
  amap_core_fluttify:
    git:
      url: https://github.com/banyungong/flutter_amap.git
      path: amap/amap_core_fluttify
#  amap_search_fluttify:
#    git:
#      url: https://github.com/banyungong/flutter_amap.git
#      path: amap/amap_search_fluttify
  amap_location_fluttify:
    git:
      url: https://github.com/banyungong/flutter_amap.git
      path: amap/amap_location_fluttify

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.amap_map_fluttify
        pluginClass: AmapMapFluttifyPlugin
      ios:
        pluginClass: AmapMapFluttifyPlugin